[package]
name = "spreadsheet-to-json"
description = "Asynchronous conversion of Excel and OpenDocument spreadsheets as well as CSV and TSV files to JSON or JSONL"
repository = "https://github.com/neilg63/to-offset"
version = "0.1.0"
edition = "2021"
categories = ["data-structures"]
license = "GPL-2.0-or-later WITH Bison-exception-2.2"

[dependencies]
calamine = { version = "0.26.1", features = ["chrono", "dates"] }
chrono = "^0.4.38"
csv = "1.3.1"
dotenv = { version = "0.15.0", features = ["clap", "cli"] }
heck = "0.5.0"
indexmap = { version = "^2.7.0", features = ["serde"] }
serde = { version = "^1.0.215", features = ["derive", "serde_derive"] }
serde_json = { version = "^1.0.133", features = ["preserve_order"] }
simple-string-patterns = "^0.3.15"
tokio = { version = ">=1.42.0, <2.0.0", features = ["full"] }
